# -------------------------------------------------------------------------------------
# Hugo Configuration
# See: https://gohugo.io/getting-started/configuration/
# -------------------------------------------------------------------------------------

title = "Wlanxww的博客"
baseURL = "https://wlanxww.com/"
theme = [
  "FixIt",
  "cmpt-flyfish",
  "shortcode-docs-bookmark",
  "cmpt-translate",
]
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
enableRobotsTXT = true
enableEmoji = true
enableGitInfo = true
relativeURLs = false
buildDrafts = false
summaryLength = 150
# ignore some build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

[languages]
  [languages.zh-cn]
    languageCode = "zh-CN"
    languageName = "简体中文"