# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo site to Server

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Deployment job
  deploy:
    environment: web-site-deploy
    runs-on: ubuntu-20.04
    env:
      HUGO_VERSION: 0.101.0
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build with Hugo
        run: |
          hugo \
            --minify \
            --baseURL ${{ steps.pages.outputs.base_url }}
      - name: copy file via ssh key
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.TENCENTCLOUD_SECRET_HOST }}
          username: ${{ secrets.TENCENTCLOUD_SECRET_USERNAME }}
          key: ${{ secrets.TENCENTCLOUD_SECRET_KEY }}
          port: ${{ secrets.TENCENTCLOUD_SECRET_PORT }}
          rm: true
          source: "public/*"
          target: ${{ secrets.TENCENTCLOUD_SECRET_TRAGET_PATH }}