name: Pull Request Valid

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ['master']

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Hugo Check
  Actions-Hugo-Check:
    environment: pr-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: ${{ vars.HUGO_VERSION || 'latest'}}
          extended: true
      - name: Clean last public
        run: rm -rf public
      - name: Build with Hugo
        run: hugo --logLevel=warn --gc --minify
